# Generated by Django 2.1.7 on 2019-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_records', models.IntegerField()),
                ('meter_consumptions', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='meters',
            options={'verbose_name': 'Meter', 'verbose_name_plural': 'Meters'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name': 'Resource type', 'verbose_name_plural': 'Resource types'},
        ),
    ]
