# Generated by Django 2.1.7 on 2019-03-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_auto_20190303_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meters.Meters'),
        ),
    ]
