# Generated by Django 2.1.7 on 2019-03-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_records_meter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='meter_consumptions',
            new_name='consumption',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='meter_records',
            new_name='record',
        ),
    ]
