# Generated by Django 2.1.7 on 2019-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0006_auto_20190310_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='consumption',
            field=models.FloatField(null=True),
        ),
    ]
