# Generated by Django 2.1.7 on 2019-03-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0007_auto_20190310_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='records',
            name='record',
            field=models.FloatField(default=0),
        ),
    ]
